import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://marsair.recruiting.thoughtworks.net/VienBui');
  await page.getByRole('link', { name: 'MarsAir' }).click();
  await page.getByRole('link', { name: 'Report an issue' }).click();
  await page.getByRole('heading', { name: 'Welcome to MarsAir!' }).click();
  await page.getByRole('heading', { name: 'Book a ticket to the red' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).click();
  await page.getByLabel('Departing').selectOption('0');
  await page.getByLabel('Returning').selectOption('1');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('Unfortunately, this schedule').click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByLabel('Returning').selectOption('3');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('Sorry, there are no more').click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByLabel('Returning').selectOption('5');
  await page.getByRole('textbox', { name: 'Promotional Code' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).fill('AF3-FJK-418');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('heading', { name: 'Search Results' }).click();
  await page.getByText('Promotional code AF3-FJK-418').click();
  await page.getByText('% discount').click();
  await page.getByText('Call now on 0800 MARSAIR to').click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).fill('AF3-FJK-417');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('Sorry, code AF3-FJK-417 is').click();
  await page.getByText('Seats available!').click();
  await page.getByRole('heading', { name: 'Search Results' }).click();
  await page.getByText('Call now on 0800 MARSAIR to').click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Promotional Code' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Promotional Code' }).fill('AF2-FJK-417');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('AF2-FJK-').click();
  await page.getByText('% discount').click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).click();
  await page.getByRole('textbox', { name: 'Promotional Code' }).dblclick();
  await page.getByRole('textbox', { name: 'Promotional Code' }).fill('JJ5-OPQ-320');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('JJ5-OPQ-').click();
  await page.getByText('Sorry, code JJ5-OPQ-320 is').click();
  await page.getByRole('link', { name: 'MarsAir' }).click();
});